# Generated by Django 4.2.7 on 2025-05-19 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(default='default-company', help_text='URL-friendly name for company subdirectory', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
