# Generated by Django 4.2.7 on 2025-05-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_company_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('COMPANY_ADMIN', 'Company Admin'), ('ADMIN', 'Admin'), ('USER', 'User')], default='USER', max_length=20),
        ),
    ]
