# Generated by Django 4.2.7 on 2025-06-05 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0005_phishingcampaign'),
        ('accounts', '0008_alter_user_options_user_company_email_id_user_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='phishing_campaign',
            field=models.ForeignKey(blank=True, help_text='Associated phishing campaign', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='email_service.phishingcampaign'),
        ),
    ]
