# Generated by Django 4.2.7 on 2025-06-13 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0009_add_name_to_emailtemplate'),
        ('accounts', '0009_email_phishing_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='email_service_config',
            field=models.ForeignKey(blank=True, help_text='Email service configuration used to send this email', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='email_service.cswordemailserv'),
        ),
    ]
