# Generated by Django 4.2.7 on 2025-06-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_email_email_service_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activated',
            field=models.BooleanField(default=False, help_text='Indicates whether the user has activated their account.', verbose_name='activated'),
        ),
    ]
