# Generated by Django 4.2.7 on 2025-06-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='number_of_allowed_users',
            field=models.IntegerField(default=1),
        ),
    ]
