# Generated by Django 4.2.7 on 2025-07-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_company_number_of_allowed_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='landing_content',
            field=models.TextField(blank=True, help_text='HTML content for the phishing landing page', null=True),
        ),
    ]
