# Generated by Django 4.2.7 on 2025-07-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_email_landing_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='landing_page_slug',
            field=models.SlugField(blank=True, help_text="Custom URL slug for the phishing landing page (e.g., 'you-got-hacked')", max_length=100, null=True),
        ),
    ]
