# Generated by Django 4.2.7 on 2025-07-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_email_landing_page_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='color_palette',
            field=models.CharField(blank=True, help_text='Comma-separated list of hex color codes, e.g., #FFFFFF,#000000', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='company_logo',
            field=models.ImageField(blank=True, help_text="Company's logo", null=True, upload_to='company_logos/'),
        ),
    ]
