# Generated by Django 4.2.7 on 2025-07-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_user_department_user_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(blank=True, help_text='Country where the company is located', max_length=100),
        ),
    ]
