# Generated by Django 4.2.7 on 2025-05-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSWordEmailServ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(help_text='SMTP server host', max_length=255)),
                ('port', models.IntegerField(help_text='SMTP server port')),
                ('host_user', models.CharField(help_text='SMTP server username', max_length=255)),
                ('host_password', models.CharField(help_text='SMTP server password', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Service Configuration',
                'verbose_name_plural': 'Email Service Configurations',
            },
        ),
    ]
