# Generated by Django 4.2.7 on 2025-05-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Email subject line', max_length=255)),
                ('content', models.TextField(help_text='Email content/body')),
                ('company', models.CharField(blank=True, help_text='Company associated with this template', max_length=255, null=True)),
                ('is_global', models.BooleanField(default=False, help_text='Whether this template is available globally to all companies')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
            },
        ),
    ]
