# Generated by Django 4.2.7 on 2025-05-24 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_department_user_department'),
        ('email_service', '0002_emailtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company associated with this template', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.company'),
        ),
    ]
