# Generated by Django 4.2.7 on 2025-05-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0003_alter_emailtemplate_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='category',
            field=models.CharField(blank=True, help_text='Category of the email template (e.g., Financial, HR, IT Support)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', help_text='Difficulty level of the phishing template', max_length=10),
        ),
    ]
