# Generated by Django 4.2.7 on 2025-06-05 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_options_user_company_email_id_user_uuid_and_more'),
        ('email_service', '0004_emailtemplate_category_emailtemplate_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhishingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(help_text='Name of the phishing campaign', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Company running this campaign', on_delete=django.db.models.deletion.CASCADE, related_name='phishing_campaigns', to='accounts.company')),
            ],
            options={
                'verbose_name': 'Phishing Campaign',
                'verbose_name_plural': 'Phishing Campaigns',
                'ordering': ['-created_at'],
            },
        ),
    ]
