# Generated by Django 4.2.7 on 2025-06-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0005_phishingcampaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='phishingcampaign',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='End date and time of the campaign', null=True),
        ),
        migrations.AddField(
            model_name='phishingcampaign',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Start date and time of the campaign', null=True),
        ),
    ]
