# Generated by Django 4.2.7 on 2025-06-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0007_alter_phishingcampaign_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phishingcampaign',
            name='end_date',
            field=models.DateField(help_text='End date of the campaign'),
        ),
        migrations.AlterField(
            model_name='phishingcampaign',
            name='start_date',
            field=models.DateField(help_text='Start date of the campaign'),
        ),
    ]
