# Generated by Django 4.2.7 on 2025-06-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0008_alter_phishingcampaign_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='name',
            field=models.SlugField(default='nn', help_text='Unique identifier for the template', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
