# Generated by Django 4.2.7 on 2025-07-03 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0009_add_name_to_emailtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='phishingcampaign',
            name='end_time',
            field=models.TimeField(blank=True, help_text='End time for sending emails each day', null=True),
        ),
        migrations.AddField(
            model_name='phishingcampaign',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Start time for sending emails each day', null=True),
        ),
    ]
