# Generated by Django 4.2.7 on 2025-07-05 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_email_landing_content'),
        ('email_service', '0010_phishingcampaign_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text='Unique identifier for the template', max_length=100, unique=True)),
                ('content', models.TextField(help_text='HTML content of the landing page')),
                ('is_global', models.BooleanField(default=False, help_text='Whether this template is available globally to all companies')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, help_text='Company associated with this template', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
            ],
            options={
                'verbose_name': 'Landing Page Template',
                'verbose_name_plural': 'Landing Page Templates',
            },
        ),
    ]
