# Generated by Django 4.2.7 on 2025-07-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0011_landingpagetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagetemplate',
            name='slug',
            field=models.SlugField(default='x', help_text='Identifier for the template, auto-generated from name', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='landingpagetemplate',
            name='name',
            field=models.CharField(help_text='Name of the landing page template', max_length=100),
        ),
    ]
