# Generated by Django 4.2.7 on 2025-07-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0012_landingpagetemplate_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpagetemplate',
            name='slug',
            field=models.SlugField(help_text='Link to the backend', max_length=100),
        ),
    ]
