# Generated by Django 4.2.7 on 2025-07-18 21:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("email_service", "0013_alter_landingpagetemplate_slug"),
    ]

    operations = []
