# Generated by Django 4.2.7 on 2025-05-31 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0008_alter_user_options_user_company_email_id_user_uuid_and_more'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LMSCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lms_campaigns', to='accounts.company')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lms_campaigns', to='courses.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_lms_campaigns', to=settings.AUTH_USER_MODEL)),
                ('questions', models.ManyToManyField(related_name='lms_campaigns', to='courses.question')),
            ],
            options={
                'verbose_name': 'LMS Campaign',
                'verbose_name_plural': 'LMS Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LMSCampaignUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('started', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_users', to='lms.lmscampaign')),
            ],
            options={
                'verbose_name': 'LMS Campaign User',
                'verbose_name_plural': 'LMS Campaign Users',
                'unique_together': {('campaign', 'email')},
            },
        ),
    ]
