# Generated by Django 4.2.7 on 2025-05-31 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lmscampaignuser',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lmscampaignuser',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='lms_campaign_participations', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='lmscampaignuser',
            unique_together={('campaign', 'user')},
        ),
        migrations.RemoveField(
            model_name='lmscampaignuser',
            name='email',
        ),
    ]
