# Generated by Django 4.2.7 on 2025-05-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_alter_lmscampaignuser_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmscampaign',
            name='end_date',
            field=models.DateField(blank=True, help_text='End date of the campaign', null=True),
        ),
        migrations.AddField(
            model_name='lmscampaign',
            name='start_date',
            field=models.DateField(blank=True, help_text='Start date of the campaign', null=True),
        ),
    ]
