# Generated by Django 4.2.7 on 2025-06-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('lms', '0003_lmscampaign_end_date_lmscampaign_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lmscampaign',
            name='course',
        ),
        migrations.AddField(
            model_name='lmscampaign',
            name='courses',
            field=models.ManyToManyField(related_name='lms_campaigns', to='courses.course'),
        ),
    ]
