# Generated by Django 4.2.7 on 2025-07-08 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_usercourseprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmscampaign',
            name='policy_report',
            field=models.BooleanField(default=False, help_text='Indicates if this campaign is for policy reporting.'),
        ),
    ]
