# Generated by Django 4.2.7 on 2025-07-08 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_lmscampaign_policy_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lmscampaign',
            old_name='policy_report',
            new_name='policy',
        ),
    ]
